### ISSUE TITLE
Sync\Login Issues

### ISSUE THREAD

**Issue by JStyle21** [oOthkOo/whatsapp-desktop#25]
### System details

* OS: 
Operating System: Gentoo Linux
Kernel Version: 5.15.32-gentoo-r1-x86_64 (64-bit)
Lang: en-us
* App Version: github
* If Linux, Desktop Environment: 
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3

### Expected behavior

Should work regularly i.e. when you open the app it opens a list of past conversation

### Actual behavior

I got sync issues, db issues and it gets stuck in an infinite loop of logging out until i remove the local files it created and try again.

### Step to reproduce the behavior

Downloaded the latest version from github, built from source for 64 bit, ran the app, synced my phone and then it got stuck in the logout loop as described above, can't get past that anymore.

**Comment by mjeveritt** [comment]
Getting the same here with Ubuntu 18.04 LTS/ KDE Plasma 5 also.

Having to use https://web.whatsapp.com in Chromium in the meantime.

Granted, I'm not holding my breath on this getting fixed without a potential fork ... :roll_eyes:

**Comment by yermulnik** [comment]
Same issue here on Ubuntu 20.04.4 LTS with latest Whatsapp Desktop version.
Latest https://gitlab.com/zerkc/whatsdesk works as expected.

**Comment by JStyle21** [comment]
So far this is the best alternative i've found
https://github.com/mimbrero/whatsapp-desktop-linux

There is also
https://github.com/WAClient/WALC

But it's more buggy right now

**Comment by oOthkOo** [comment]
Hello

The new version of the application **0.5.2** solves this problem which is due to a check of the Meta servers on the user agent of the browser which launches the requests.

With this new version you can specify a list of user agents in the `agents.json` file which is located at the root of the folder where the application is located. At each launch, the application will randomly choose a user agent from the list.

Enjoy ;-)

**Comment by yermulnik** [comment]
@oOthkOo Thank you!
